#!/bin/bash

#
# 17Oct2019, Maiko (VE4KLM), a simple script I wrote to parse the ftpusers
# file and create new user/password entries in the recently added JNOS 2.0
# password management system, fixed a few things - ready to go 18 Oct 2019,
# then a major rewrite of sorts for j2pwmgrV2, finally done January 2020.
#
# The following 2 files MUST exist in your jnos root directory :
#
#  jnospwmgr        (JNOS 2.0 password manager generated by the compile)
#
#  importFTPUSERSpasswords.sh     (this import script)
#
# What this script does ?
#
#  parses the ftpusers file (from stdin), and for any line containing a valid
#  password, it will call the jnospwmgr program to create a new entry in the
#  recenty added JNOS 2.0 password management system.
#
# What do I have to do in the JNOS compile to support this ?
#
#  Make sure to add this new directive below to your config.h :
#
#   #define GET_PASSWORD_FROM_J2PWMGR
#
# How to use it (in this example I use /jnos as the jnos root directory) :
#
#  cd /jnos
#
#  sh importFTPUSERSpasswords.sh < ftpusers
#     

# 16Jan2020, make sure 'users' directory exists, one less thing
# for the sysop to worry about or possibly forget. The -p option
# suppresses any error message if directory exists already.

mkdir -p users

while read  user  password  rootdir  perms
do

	if [ "$password" != '*' ]; then
		./jnospwmgr -a $user -p $password -r $rootdir -# $perms;
	else
		./jnospwmgr -a $user -p nopassword -r $rootdir -# $perms;
	fi
done

